cask "font-source-sans" do
  version "3.042R"
  sha256 "604d99a42b871e19de3654b936fb145db7094941efcdca4981d742d291382b94"

  url "https://github.com/adobe-fonts/source-sans/releases/download/#{version}/source-sans-#{version}.zip"
  appcast "https://github.com/adobe-fonts/source-sans/releases.atom"
  name "Source Sans"
  desc "Fonts designed for user interfaces"
  homepage "https://github.com/adobe-fonts/source-sans"

  font "OTF/SourceSans3-Black.otf"
  font "OTF/SourceSans3-BlackIt.otf"
  font "OTF/SourceSans3-Bold.otf"
  font "OTF/SourceSans3-BoldIt.otf"
  font "OTF/SourceSans3-ExtraLight.otf"
  font "OTF/SourceSans3-ExtraLightIt.otf"
  font "OTF/SourceSans3-It.otf"
  font "OTF/SourceSans3-Light.otf"
  font "OTF/SourceSans3-LightIt.otf"
  font "OTF/SourceSans3-Regular.otf"
  font "OTF/SourceSans3-Semibold.otf"
  font "OTF/SourceSans3-SemiboldIt.otf"
  font "VAR/SourceSans3VF-Italic.otf"
  font "VAR/SourceSans3VF-Roman.otf"
end
